import javax.annotation.Nullable

plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev' version "${moddevgradle_version}"
}

version = "${minecraft_version}-${mod_version}-neoforge"
group = "net.zepalesque.zenith"

base {
    archivesName = mod_id
}

// Mojang ships Java 21 to end users in 1.21+, so your mod should target Java 21.
java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    runs {
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'

            logLevel = org.slf4j.event.Level.DEBUG
        }

        client {
            client()
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id

            @Nullable String username = System.getenv "MC_USR_DEV";
            if (username != null) programArguments.addAll '--username', username

            @Nullable String uuid = System.getenv "MC_UUID_DEV";
            if (uuid != null) programArguments.addAll '--uuid', uuid
        }

        server {
            server()
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
            programArgument '--nogui'
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
    parchment {
        minecraftVersion = "${mappings_mc_ver}"
        mappingsVersion = "${mappings}"
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

sourceSets.main.java { srcDir 'src/generated/java' }

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {}

repositories {
    maven { url = 'https://maven.parchmentmc.org' }
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            mod_id                     : mod_id,
            mod_name                   : mod_name,
            mod_version                : mod_version,
            mod_license                : mod_license,
            mod_tracker                : mod_tracker,
            mod_authors                : mod_authors,
            mod_description            : mod_description,
            minecraft_version          : minecraft_version,
            minecraft_version_range    : minecraft_version_range,
            neo_version                : neo_version,
            neo_version_range          : neo_version_range,
            loader_version_range       : loader_version_range
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates/META-INF"
    into "build/generated/sources/modMetadata/META-INF"
}
sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

compileJava {
    options.incremental = false
}

tasks.register('sourceJar', Jar) {
    dependsOn 'classes'
    from sourceSets.main.allSource
    archiveClassifier = 'sources'
}

tasks.register('genInfo', ProcessResources) {

    File root = file('src/main')
    File java = new File(root, 'java')
    File template = new File(root, 'templates/package-info-template.java')
    File genJava = file('src/generated/java')

    genJava.deleteDir()
    int i;

    java.eachDirRecurse { dir ->
        if (dir == java || dir.parentFile == java) return
        String relative = dir.absolutePath.replace(java.absolutePath + File.separator, '')
        String packageName = relative.replace(File.separator, '.')

        if (!packageName) return
        File genDir = new File(genJava, relative)
        if (!genDir.exists()) genDir.mkdirs()

        i++
        if (dir.listFiles((FileFilter) File::isFile).length > 0) {
            File infoFile = new File(genDir, 'package-info.java')
            String contents = template.text.replace("\${directory}", packageName)
            infoFile.text = contents
        }
    }
    println("\nCreated package-info.java in " + i + " subdirectories\n")
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId project.archivesBaseName
            artifact project.jar
            artifact project.sourceJar
        }
    }
    repositories {
        maven {
            name = "GitHubPackages"
            url = "https://maven.pkg.github.com/Zepalesque/Zenith"
            credentials {
                username = System.getenv("GITHUB_ACTOR")
                password = System.getenv("GITHUB_TOKEN")
            }
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
