modLoader="javafml"
loaderVersion="[2,)"
license="All rights reserved"

[[mods]]
modId="zenith"
version="${mod_version}"
displayName="${mod_name}"
displayURL = "https://github.com/Zepalesque/Zenith"
logoFile = "zenith.png"
authors = "Zepalesque"
description = '''
 '''
[[dependencies.zenith]] #optional
modId="neoforge" #mandatory
type="required" #mandatory
versionRange="[20.4,)" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.zenith]]
modId="minecraft"
type="required"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"